<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;



class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'title_for_web' => 'Who’s moving in?',
                'title_for_app' => 'Who’s moving in?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 1,
                'question_order_for_app' => 1,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 1
            ],
            [
                'title_for_web' => 'Your name',
                'title_for_app' => 'Your name',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 2,
                'question_order_for_app' => 2,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 2
            ],
            [
                'title_for_web' => 'Date of birth',
                'title_for_app' => 'Date of birth',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 3,
                'question_order_for_app' => 3,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 2
            ],
            [
                'title_for_web' => 'What gender best describes you?',
                'title_for_app' => 'What gender best describes you?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 4,
                'question_order_for_app' => 4,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 3
            ],
            [
                'title_for_web' => 'What sexuality best describes you?',
                'title_for_app' => 'What sexuality best describes you?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 5,
                'question_order_for_app' => 5,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 3
            ],
            [
                'title_for_web' => 'What is your current employment status?',
                'title_for_app' => 'What is your current employment status?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 6,
                'question_order_for_app' => 6,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 4
            ],
            [
                'title_for_web' => 'Do you drink?',
                'title_for_app' => 'Do you drink?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 7,
                'question_order_for_app' => 7,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 5
            ],
            [
                'title_for_web' => 'Do you smoke?',
                'title_for_app' => 'Do you smoke?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 8,
                'question_order_for_app' => 8,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 5
            ],
            [
                'title_for_web' => 'Do you have any dietary requirements?',
                'title_for_app' => 'Do you have any dietary requirements?',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 9,
                'question_order_for_app' => 9,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 5
            ],
            [
                'title_for_web' => 'Are you a morning person or a night owl?',
                'title_for_app' => 'Are you a morning person or a night owl?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 10,
                'question_order_for_app' => 10,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'Are you a clean freak or easygoing cleaner?',
                'title_for_app' => 'Are you a clean freak or easygoing cleaner?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 11,
                'question_order_for_app' => 11,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'Are you more introverted or extroverted?',
                'title_for_app' => 'Are you more introverted or extroverted?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 12,
                'question_order_for_app' => 12,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'Do you feel hot or cold easily?',
                'title_for_app' => 'Do you feel hot or cold easily?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 13,
                'question_order_for_app' => 13,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'Do you cook or eat out more often?',
                'title_for_app' => 'Do you cook or eat out more often?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 14,
                'question_order_for_app' => 14,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'Are you a homebody or always out and about?',
                'title_for_app' => 'Are you a homebody or always out and about?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 15,
                'question_order_for_app' => 15,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'Do you prefer to share or keep things separate?',
                'title_for_app' => 'Do you prefer to share or keep things separate?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 16,
                'question_order_for_app' => 16,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'Are you a social host or more reserved?',
                'title_for_app' => 'Are you a social host or more reserved?',
                'sub_title_for_app' => null,
                'type_for_app' => 4,
                'type_for_web' => 4,
                'showing_in' => 3,
                'question_order_for_web' => 17,
                'question_order_for_app' => 17,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 6
            ],
            [
                'title_for_web' => 'What is your ethnicity?',
                'title_for_app' => 'What is your ethnicity?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 18,
                'question_order_for_app' => 18,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 7
            ],
            [
                'title_for_web' => 'Open to Team Ups?',
                'title_for_app' => 'Open to Team Ups?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 19,
                'question_order_for_app' => 19,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],
            [
                'title_for_web' => 'What suburbs are you interested in?',
                'title_for_app' => 'What suburbs are you interested in?',
                'sub_title_for_app' => 'We recommend choosing at least 4.',
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 20,
                'question_order_for_app' => 20,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],
            [
                'title_for_web' => 'What is your preferred stay length?',
                'title_for_app' => 'What is your preferred stay length?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 21,
                'question_order_for_app' => 21,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],
            [
                'title_for_web' => 'What date are you available?',
                'title_for_app' => 'What date are you available?',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 22,
                'question_order_for_app' => 22,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],
            [
                'title_for_web' => 'What is your rental budget range?',
                'title_for_app' => 'What is your rental budget range?',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 23,
                'question_order_for_app' => 23,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],
            [
                'title_for_web' => 'Rental History',
                'title_for_app' => 'Rental History',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 24,
                'question_order_for_app' => 24,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],
            [
                'title_for_web' => 'Property Preferences',
                'title_for_app' => 'Property Preferences',
                'sub_title_for_app' => 'Room Furnishings',
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 25,
                'question_order_for_app' => 25,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],
            [
                'title_for_web' => 'What languages do you speak?',
                'title_for_app' => 'What languages do you speak?',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 26,
                'question_order_for_app' => 26,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 10
            ],
            [
                'title_for_web' => 'Political Views',
                'title_for_app' => 'Political Views',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 27,
                'question_order_for_app' => 27,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 10
            ],
            [
                'title_for_web' => 'Open to Overnight Guests',
                'title_for_app' => 'Open to Overnight Guests',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 28,
                'question_order_for_app' => 28,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 10
            ],
            [
                'title_for_web' => 'Pets',
                'title_for_app' => 'Pets',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 29,
                'question_order_for_app' => 29,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 10
            ],
            [
                'title_for_web' => 'Choose 3 things you’re really into',
                'title_for_app' => 'Choose 3 things you’re really into',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 30,
                'question_order_for_app' => 30,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 11
            ],
            [
                'title_for_web' => 'What is your religion?',
                'title_for_app' => 'What is your religion?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 31,
                'question_order_for_app' => 31,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 12
            ],
            // question_for => 13
            [
                'title_for_web' => 'My ideal night at home involves',
                'title_for_app' => 'My ideal night at home involves',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 32,
                'question_order_for_app' => 32,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 13,
            ],
            [
                'title_for_web' => 'We’re the same type of weird if',
                'title_for_app' => 'We’re the same type of weird if',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 33,
                'question_order_for_app' => 33,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 13,
            ],
            [
                'title_for_web' => "A show I'll rewatch til the end of time",
                'title_for_app' => "A show I'll rewatch til the end of time",
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 34,
                'question_order_for_app' => 34,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 13,
            ],
            [
                'title_for_web' => "Don't hate me if I",
                'title_for_app' => "Don't hate me if I",
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 35,
                'question_order_for_app' => 35,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 13,
            ],
            [
                'title_for_web' => 'My housemate green flag is',
                'title_for_app' => 'My housemate green flag is',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 36,
                'question_order_for_app' => 36,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 13,
            ],
            [
                'title_for_web' => 'My go-to cleaning soundtrack is',
                'title_for_app' => 'My go-to cleaning soundtrack is',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 37,
                'question_order_for_app' => 37,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 13,
            ],

            // question_for => 14
            [
                'title_for_web' => 'Instant housemate ick:',
                'title_for_app' => 'Instant housemate ick:',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 38,
                'question_order_for_app' => 38,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 14,
            ],
            [
                'title_for_web' => "If something’s bothering me, I'll probably",
                'title_for_app' => "If something’s bothering me, I'll probably",
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 39,
                'question_order_for_app' => 39,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 14,
            ],
            [
                'title_for_web' => "Let's make sure we're on the same page about",
                'title_for_app' => "Let's make sure we're on the same page about",
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 40,
                'question_order_for_app' => 40,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 14,
            ],
            [
                'title_for_web' => 'One thing I can’t live with is',
                'title_for_app' => 'One thing I can’t live with is',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 41,
                'question_order_for_app' => 41,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 14,
            ],
            [
                'title_for_web' => 'I’m big on communication when it comes to',
                'title_for_app' => 'I’m big on communication when it comes to',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 42,
                'question_order_for_app' => 42,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 14,
            ],
            [
                'title_for_web' => 'A boundary of mine is',
                'title_for_app' => 'A boundary of mine is',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 43,
                'question_order_for_app' => 43,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 14,
            ],

            // question_for => 15
            [
                'title_for_web' => 'My least favourite chore',
                'title_for_app' => 'My least favourite chore',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 44,
                'question_order_for_app' => 44,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 15,
            ],
            [
                'title_for_web' => 'You can always borrow my',
                'title_for_app' => 'You can always borrow my',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 45,
                'question_order_for_app' => 45,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 15,
            ],
            [
                'title_for_web' => 'My cleaning style in 3 emojis',
                'title_for_app' => 'My cleaning style in 3 emojis',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 46,
                'question_order_for_app' => 46,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 15,
            ],
            [
                'title_for_web' => "When I’m home, I’m mostly found",
                'title_for_app' => "When I’m home, I’m mostly found",
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 47,
                'question_order_for_app' => 47,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 15,
            ],
            [
                'title_for_web' => 'My ideal shared bathroom setup looks like',
                'title_for_app' => 'My ideal shared bathroom setup looks like',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 48,
                'question_order_for_app' => 48,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 15,
            ],
            [
                'title_for_web' => 'Food sharing? All in, maybe sometimes, or hands off?',
                'title_for_app' => 'Food sharing? All in, maybe sometimes, or hands off?',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 49,
                'question_order_for_app' => 49,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 15,
            ],

            // question_for => 16 (continuing from existing order 48+)
            [
                'title_for_web' => 'One house rule I swear by is',
                'title_for_app' => 'One house rule I swear by is',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 50,
                'question_order_for_app' => 50,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 16,
            ],
            [
                'title_for_web' => 'I’m fine with guests unless',
                'title_for_app' => 'I’m fine with guests unless',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 51,
                'question_order_for_app' => 51,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 16,
            ],
            [
                'title_for_web' => 'Please don’t touch my',
                'title_for_app' => 'Please don’t touch my',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 52,
                'question_order_for_app' => 52,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 16,
            ],
            [
                'title_for_web' => 'My noise limit ends at',
                'title_for_app' => 'My noise limit ends at',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 53,
                'question_order_for_app' => 53,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 16,
            ],
            [
                'title_for_web' => 'My take on splitting shared costs is',
                'title_for_app' => 'My take on splitting shared costs is',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 54,
                'question_order_for_app' => 54,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 16,
            ],
            [
                'title_for_web' => 'When it comes to hosting',
                'title_for_app' => 'When it comes to hosting',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 55,
                'question_order_for_app' => 55,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 16,
            ], 
            [
                'title_for_web' => 'What type of accommodation are you offering?',
                'title_for_app' => 'What type of accommodation are you offering?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 56,
                'question_order_for_app' => 56,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 17,
            ],
            [
                'title_for_web' => 'Property Address',
                'title_for_app' => 'Property Address',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 57,
                'question_order_for_app' => 57,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 18,
            ],
            [
                'title_for_web' => 'Total bedrooms',
                'title_for_app' => 'Total bedrooms',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 58,
                'question_order_for_app' => 58,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 18,
            ],
            [
                'title_for_web' => 'Total bathrooms',
                'title_for_app' => 'Total bathrooms',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 59,
                'question_order_for_app' => 59,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 18,
            ],
            [
                'title_for_web' => 'Parking Available',
                'title_for_app' => 'Parking Available',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 60,
                'question_order_for_app' => 60,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 18,
            ],
            [
                'title_for_web' => 'WiFi',
                'title_for_app' => 'WiFi',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 61,
                'question_order_for_app' => 61,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 18,
            ],
            [
                'title_for_web' => 'Home Accessibility',
                'title_for_app' => 'Home Accessibility',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 62,
                'question_order_for_app' => 62,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 18,
            ],
            [
                'title_for_web' => 'Property Facilities',
                'title_for_app' => 'Property Facilities',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 63,
                'question_order_for_app' => 63,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 18,
            ],
            [
                'title_for_web' => 'Who lives in the property?',
                'title_for_app' => 'Who lives in the property?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 64,
                'question_order_for_app' => 64,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 19,
            ],
             [
                'title_for_web' => 'Say something about the property',
                'title_for_app' => 'Say something about the property',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 80,
                'question_order_for_app' => 80,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 21,
            ],
            [
                'title_for_web' => 'Say something about yourself and other Homees living in the home',
                'title_for_app' => 'Say something about yourself and other Homees living in the home',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 81,
                'question_order_for_app' => 81,
                'section' => 2,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 21,
            ],
            [
                'title_for_web' => 'Room Name',
                'title_for_app' => 'Room Name',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 65,
                'question_order_for_app' => 65,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 22,
            ],
            [
                'title_for_web' => 'Room Type',
                'title_for_app' => 'Room Type',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 66,
                'question_order_for_app' => 66,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 22,
            ],
            [
                'title_for_web' => 'Room Furnishings',
                'title_for_app' => 'Room Furnishings',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 67,
                'question_order_for_app' => 67,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 22,
            ],
            [
                'title_for_web' => 'Bathroom',
                'title_for_app' => 'Bathroom',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 68,
                'question_order_for_app' => 68,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 22,
            ],
            [
                'title_for_web' => 'Bed Size',
                'title_for_app' => 'Bed Size',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 69,
                'question_order_for_app' => 69,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 23,
            ],
            [
                'title_for_web' => 'Room Furnishings and Features',
                'title_for_app' => 'Room Furnishings and Features',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 70,
                'question_order_for_app' => 70,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 23,
            ],
            [
                'title_for_web' => 'Weekly Rent',
                'title_for_app' => 'Weekly Rent',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 71,
                'question_order_for_app' => 71,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 24,
            ],
            [
                'title_for_web' => 'Bills included in rent',
                'title_for_app' => 'Bills included in rent',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 72,
                'question_order_for_app' => 72,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 24,
            ],
            [
                'title_for_web' => 'Add Approximate cost of bills per month',
                'title_for_app' => 'Add Approximate cost of bills per month',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 73,
                'question_order_for_app' => 73,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 24,
            ],
            [
                'title_for_web' => 'Bond',
                'title_for_app' => 'Bond',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 74,
                'question_order_for_app' => 74,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 24,
            ],
            [
                'title_for_web' => 'Availability',
                'title_for_app' => 'Availability',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 75,
                'question_order_for_app' => 75,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 25,
            ],
            [
                'title_for_web' => 'Minimum Length of Stay',
                'title_for_app' => 'Minimum Length of Stay',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 76,
                'question_order_for_app' => 76,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 25,
            ],     
            [
                'title_for_web' => 'Maximum Length of Stay',
                'title_for_app' => 'Maximum Length of Stay',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 77,
                'question_order_for_app' => 77,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 25,
            ], 
            [
                'title_for_web' => 'Housemate preferences',
                'title_for_app' => 'Housemate preferences',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 78,
                'question_order_for_app' => 78,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 27,
            ],
            [
                'title_for_web' => 'Accepting of',
                'title_for_app' => 'Accepting of',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 79,
                'question_order_for_app' => 79,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 27,
            ],
             [
                'title_for_web' => 'Property Preferences',
                'title_for_app' => 'Property Preferences',
                'sub_title_for_app' => 'Internet',
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 82,
                'question_order_for_app' => 82,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],

             [
                'title_for_web' => 'Property Preferences',
                'title_for_app' => 'Property Preferences',
                'sub_title_for_app' => 'Bathroom Type',
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 83,
                'question_order_for_app' => 83,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],

             [
                'title_for_web' => 'Property Preferences',
                'title_for_app' => 'Property Preferences',
                'sub_title_for_app' => 'Parking',
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 84,
                'question_order_for_app' => 84,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ],

             [
                'title_for_web' => 'Property Preferences',
                'title_for_app' => 'Property Preferences',
                'sub_title_for_app' => 'Max number of roommates',
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 85,
                'question_order_for_app' => 85,
                'section' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 8
            ], 
             [
                'title_for_web' => 'You can upload up to 10 images & 1 video for a virtual tour feel.',
                'title_for_app' => 'You can upload up to 10 images & 1 video for a virtual tour feel.',
                'sub_title_for_app' => null,
                'type_for_app' => 2,
                'type_for_web' => 2,
                'showing_in' => 3,
                'question_order_for_web' => 86,
                'question_order_for_app' => 86,
                'section' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 26,
            ], 
             [
                'title_for_web' => 'First name',
                'title_for_app' => 'First name',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 87,
                'question_order_for_app' => 87,
                'section' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 19,
            ], 
             [
                'title_for_web' => 'Last name',
                'title_for_app' => 'Last name',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 88,
                'question_order_for_app' => 88,
                'section' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 19,
            ],
            [
                'title_for_web' => 'Age',
                'title_for_app' => 'Age',
                'sub_title_for_app' => null,
                'type_for_app' => 3,
                'type_for_web' => 3,
                'showing_in' => 3,
                'question_order_for_web' => 89,
                'question_order_for_app' => 89,
                'section' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 19,
            ],
             [
                'title_for_web' => 'What gender best describes you?',
                'title_for_app' => 'What gender best describes you?',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 90,
                'question_order_for_app' => 90,
                'section' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 19,
            ],
            [
                'title_for_web' => 'Ethnicity',
                'title_for_app' => 'Ethnicity',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 91,
                'question_order_for_app' => 91,
                'section' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 19,
            ],
            [
                'title_for_web' => 'Upload a photo of this housemate. Photo = trust = more views 📸',
                'title_for_app' => 'Upload a photo of this housemate. Photo = trust = more views 📸',
                'sub_title_for_app' => null,
                'type_for_app' => 1,
                'type_for_web' => 1,
                'showing_in' => 3,
                'question_order_for_web' => 92,
                'question_order_for_app' => 92,
                'section' => 4,
                'created_at' => now(),
                'updated_at' => now(),
                'question_for' => 19,
            ],
        ]; 
        
        $data = array_map(function ($item) {
            $item['slug'] = Str::slug($item['title_for_web'] ?? '');
            return $item;
        }, $data);

        DB::table(config('tables.questions'))->insert($data);
    }
}
